apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: go-hrdrsrow
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-hrdrsrow 
  name: go-hrdrsrow
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: go-hrdrsrow
    weight: 100 
